AllCops:
  Exclude:
    - lib/tasks/cucumber.rake
    - features/step_definitions/email_steps.rb
    - 'db/**/*'
    
# C: Missing top-level module documentation comment.
Style/Documentation:
  Enabled: false

# C: Prefer inject over reduce.
Style/CollectionMethods:
  PreferredMethods:
    reduce: 'inject'

# C: Use each_with_object instead of inject.
Style/EachWithObject:
  Enabled: false

# don't enforce single- or double-quotes
Style/StringLiterals:
  Enabled: false

# library method, leave the violation
Style/PerlBackrefs:
  Exclude:
    - features/support/paths.rb

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# This never works for validations
Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

# all the cuke syntax fails
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*'

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

Style/PredicateName:
  Exclude:
    - app/models/user.rb
    - app/models/guest.rb
