AllCops:
  Exclude:
    - lib/tasks/cucumber.rake
    - features/step_definitions/email_steps.rb
    
# C: Missing top-level module documentation comment.
Style/Documentation:
  Enabled: false

# C: Prefer reduce over inject.
Style/CollectionMethods:
  Enabled: false

# C: Use each_with_object instead of inject.
Style/EachWithObject:
  Enabled: false

# C: Prefer single-quoted strings when you don't need string interpolation or special symbols
Style/StringLiterals:
  Enabled: false

# I like trailing commas, thanks.
Style/TrailingComma:
  Enabled: false

# This never works for validations
Style/AlignHash:
  Enabled: false

# all the cuke syntax fails
Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
